name: qik_pharma_mobile
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+3

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  page_transition: "^2.0.5"
  permission_handler: ^11.3.1
  shared_preferences: ^2.0.13
  url_launcher: ^6.1.7
  top_snackbar_flutter: ^3.1.0
  dotted_border: ^2.0.0+2
  flutter_spinkit: ^5.1.0
  flutter_bloc: ^8.0.1
  floating_bottom_navigation_bar: ^1.5.2
  equatable: ^2.0.3
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.0.0
  flutter_svg: ^2.0.9
  google_sign_in: ^6.2.1
  dots_indicator: ^3.0.0
  pin_code_text_field: ^1.8.0
  image_picker: ^1.1.2
  flutter_paystack_naza: ^1.0.4
  dio: ^5.4.3+1
  loggy: ^2.0.3
  flutter_styled_toast: ^2.1.3
  intl: ^0.19.0
  data_connection_checker_tv: ^0.3.5-nullsafety
  connectivity_plus: ^6.0.3
  flutter_cache_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/db/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
